config/routes.rb
Rails.application.routes.draw do
  get 'coreg/index'

  root 'homes#index'
  resources :homes do
    collection do
      get :co_reg
      get :life
      get :health
      get :auto
      get :home
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coreg_controller.rb
class CoregController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  def co_reg

  end
  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/coreg/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sum0 Publisher Test Environment: Co-reg Feed</h1>
<iframe src="https://frozen-fjord-36346.herokuapp.com/api/v1/ad_serve/23/lead_ad" width="100%" frameborder="0" id="iframe-id" allowfullscreen scrolling="no"></iframe>
<script>
  var h= ($('iframe').contents().height() );
  $('iframe').css({
    'height': 6 * h
  });
</script>

app/views/homes/_form.html.erb
<%= form_for(home, :html => { :name => "myForm" , :id=> "myForm"}) do |f| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>
      <ul>
        <% home.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name ,class: 'form-control required lettersonly', name: "home[name]", minlength: 2%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
   function getURLParameter(ad_token) {
    return decodeURIComponent((new RegExp('[?|&]' + ad_token + '=' + '([^&;]+?)(&|#|;|$)').exec(location.search) || [null, ''])[1].replace(/\+/g, '%20')) || null;
  }
  param = getURLParameter('ad_token');
  var forms = document.forms;
  for(var i=0;i<forms.length;i++)
  {
    var f = document.forms[i].getElementsByTagName("input");
    var flag = 0;
    for (var j=0; j<f.length; j++) {
      if (f[j].type.toLowerCase() === "password" || f[j].type.toLowerCase() === "search" || (f[j].innerHTML.indexOf('search') > -1)) 
      {
        flag = 1;
        console.log("search box");
        break;
        } 
      }
      if(flag == 0){
      console.log("no passwrd field")
      forms[i].addEventListener('submit', function(evt){
        var xhttp = new XMLHttpRequest();
        var url = "https://frozen-fjord-36346.herokuapp.com/api/v1/ad_serve/12/lead_track?ad_token=" + param ;
        xhttp.open("GET", url, true);
        xhttp.send(param);
      });
    }
  }
  if (!localStorage['done']) {
        localStorage['done'] = 'true';
        var xhttpreq = new XMLHttpRequest();
        var url ="https://frozen-fjord-36346.herokuapp.com/api/v1/ad_serve/12/code_tracker" ;
        xhttpreq.open("POST", url, true);
        xhttpreq.send();  
   }
</script>

app/views/homes/auto.html.erb
<p id="notice"><%= notice %></p>

<h1 style="line-height:35px;">Sum0 Publisher Test Environment: Click Feed/Auto Insurance</h1>

<iframe src="https://frozen-fjord-36346.herokuapp.com/api/v1/ad_serve/20/click_ad" width="100%" frameborder="0" allowfullscreen scrolling="no"></iframe>



<script>
  var h= ($('iframe').contents().height() );
  $('iframe').css({
    'height': 10 * h
  });
</script>

app/views/homes/co_reg.html.erb
<h1>Sum0 Publisher Test Environment: Co-Reg/Midpath</h1>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/health.html.erb
<p id="notice"><%= notice %></p>

<h1 style="line-height:35px;">Sum0 Publisher Test Environment: Click Feed/Health Insurance</h1>

<iframe src="https://frozen-fjord-36346.herokuapp.com/api/v1/ad_serve/22/click_ad" width="100%" frameborder="0" allowfullscreen scrolling="no"></iframe>



<script>
  var h= ($('iframe').contents().height() );
  $('iframe').css({
    'height': 10 * h
  });
</script>

app/views/homes/home.html.erb
<p id="notice"><%= notice %></p>

<h1 style="line-height:35px;">Sum0 Publisher Test Environment: Click Feed/Home Insurance</h1>

<iframe src="https://frozen-fjord-36346.herokuapp.com/api/v1/ad_serve/7/click_ad" width="100%" frameborder="0" allowfullscreen scrolling="no"></iframe>



<script>
  var h= ($('iframe').contents().height() );
  $('iframe').css({
    'height': 10 * h
  });
</script>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="line-height:35px;">Sum0 Publisher Test Environment: Click Feed</h1>

<iframe src="https://frozen-fjord-36346.herokuapp.com/api/v1/ad_serve/51/click_ad" width="100%" frameborder="0" allowfullscreen scrolling="no"></iframe>



<script>
  var h= ($('iframe').contents().height() );
  $('iframe').css({
    'height': 10 * h
  });
</script>

app/views/homes/life.html.erb
<p id="notice"><%= notice %></p>

<h1 style="line-height:35px;">Sum0 Publisher Test Environment: Click Feed/Life INsurance</h1>

<iframe src="https://frozen-fjord-36346.herokuapp.com/api/v1/ad_serve/21/click_ad" width="100%" frameborder="0" allowfullscreen scrolling="no"></iframe>



<script>
  var h= ($('iframe').contents().height() );
  $('iframe').css({
    'height': 10 * h
  });
</script>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @home.name %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>